<a href="https://colab.research.google.com/github/JVV06/Synth-dataset/blob/main/TGAN_preprocessing_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

# Upload file in Colab first
from google.colab import files
uploaded = files.upload()

Saving health_indicators_ready.csv to health_indicators_ready (1).csv

In [ ]:
# Load dataset
df = pd.read_csv(list(uploaded.keys())[0], sep=';')

# Preview
df.head()

,GHO (DISPLAY),YEAR (DISPLAY),DIMENSION (NAME),Numeric
0,Population using at least basic sanitation ser...,2017.0,Urban,75.223231943
1,Prevalence of overweight among children and ad...,2017.0,Female,28.953755
2,Tobacco Warning: W2c smokeless tobacco packagi...,2014.0,The quit line number must appear on smokeless ...,NaN
3,Proportion of population with primary reliance...,1995.0,Rural,4.4
4,"Mean Non-HDL cholesterol, crude",1993.0,Male,3.0

In [ ]:
# Standardize column names (important)
df.columns = df.columns.str.strip().str.replace(" ", "_")

# Example expected names:
# Indicator, Year, Dimension, Numeric

# Drop missing values
df = df.dropna()

# Remove duplicates
df = df.drop_duplicates()

print("Shape after cleaning:", df.shape)

Shape after cleaning: (15338, 4)

**Rename Columns (for clarity)**

In [ ]:
df = df.rename(columns={
    'GHO_(DISPLAY)': 'Indicator',
    'YEAR_(DISPLAY)': 'Year',
    'DIMENSION_(NAME)': 'Dimension',
    'Numeric': 'Value'
})

In [ ]:
# Preview
df.head()

,Indicator,Year,Dimension,Value
0,Population using at least basic sanitation ser...,2017.0,Urban,75.223231943
1,Prevalence of overweight among children and ad...,2017.0,Female,28.953755
3,Proportion of population with primary reliance...,1995.0,Rural,4.4
4,"Mean Non-HDL cholesterol, crude",1993.0,Male,3.0
8,Proportion of population with primary reliance...,2007.0,Urban,82.4

**Ensure Correct Data Types**

In [ ]:
# Convert Year to integer
df['Year'] = df['Year'].astype(int)

# Convert Value to numeric
df['Value'] = pd.to_numeric(df['Value'], errors='coerce')

# Drop rows where Value failed conversion
df = df.dropna(subset=['Value'])

# Reset index
df = df.reset_index(drop=True)

**Reduce Cardinality (IMPORTANT for GAN performance)**

In [ ]:
# Keep top 20 most frequent indicators
top_indicators = df['Indicator'].value_counts().nlargest(20).index

df = df[df['Indicator'].isin(top_indicators)]

print("Remaining indicators:", df['Indicator'].nunique())

Remaining indicators: 20

**Encode Categorical Variables (CTGAN handles categories, but optional encoding helps)**

For CTGAN (SDV), you actually keep them as strings, NOT numeric encoding.

So DO NOT label encode — instead:

In [ ]:
# Ensure categorical columns are strings
df['Indicator'] = df['Indicator'].astype(str)
df['Dimension'] = df['Dimension'].astype(str)

**Normalize Numerical Variable (Optional but recommended)**

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

df['Value_scaled'] = scaler.fit_transform(df[['Value']])

You can either:

Use Value directly (CTGAN handles it)
OR use Value_scaled (more stable training)

**Final Dataset for GAN**

Select only required columns:

In [ ]:
df_final = df[['Indicator', 'Year', 'Dimension', 'Value']]

df_final.head()

,Indicator,Year,Dimension,Value
1,Prevalence of overweight among children and ad...,2017,Female,28.953755
2,Proportion of population with primary reliance...,1995,Rural,4.400000
4,Proportion of population with primary reliance...,2007,Urban,82.400000
6,Prevalence of thinness among children and adol...,2005,Male,6.880980
8,"Alcohol, recorded per capita (15+) consumption...",2018,Other alcoholic beverages,0.730000

**Save Clean Dataset (important for reproducibility)**

In [ ]:
df_final.to_csv("clean_health_data.csv", index=False)

files.download("clean_health_data.csv")

**Define Metadata for CTGAN (VERY IMPORTANT STEP)**

In [ ]:
# Install sdv library if not already installed
!pip install sdv

from sdv.metadata import SingleTableMetadata

metadata = SingleTableMetadata()

metadata.detect_from_dataframe(df_final)

metadata

Collecting sdv
  Downloading sdv-1.35.0-py3-none-any.whl.metadata (14 kB)
Collecting boto3<2.0.0,>=1.28 (from sdv)
  Downloading boto3-1.42.73-py3-none-any.whl.metadata (6.7 kB)
Collecting botocore<2.0.0,>=1.31 (from sdv)
  Downloading botocore-1.42.73-py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: cloudpickle>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from sdv) (3.1.2)
Requirement already satisfied: graphviz>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from sdv) (0.21)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from sdv) (2.0.2)
Requirement already satisfied: pandas<3,>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from sdv) (2.2.2)
Requirement already satisfied: tqdm>=4.29 in /usr/local/lib/python3.12/dist-packages (from sdv) (4.67.3)
Collecting copulas>=0.12.1 (from sdv)
  Downloading copulas-0.14.1-py3-none-any.whl.metadata (9.7 kB)
Collecting ctgan>=0.11.1 (from sdv)
  Downloading ctgan-0.12.1-py3-none-any.whl.metadata (10 kB)
Collecting deepecho>=0.7.0 (from sdv)
  Downloading deepecho-0.8.1-py3-none-any.whl.metadata (11 kB)
Collecting rdt>=1.18.2 (from sdv)
  Downloading rdt-1.20.0-py3-none-any.whl.metadata (11 kB)
Collecting sdmetrics>=0.28.0 (from sdv)
  Downloading sdmetrics-0.28.0-py3-none-any.whl.metadata (9.9 kB)
Requirement already satisfied: platformdirs>=4.0 in /usr/local/lib/python3.12/dist-packages (from sdv) (4.9.4)
Requirement already satisfied: pyyaml>=6.0.1 in /usr/local/lib/python3.12/dist-packages (from sdv) (6.0.3)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3<2.0.0,>=1.28->sdv)
  Downloading jmespath-1.1.0-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer<0.17.0,>=0.16.0 (from boto3<2.0.0,>=1.28->sdv)
  Downloading s3transfer-0.16.0-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /usr/local/lib/python3.12/dist-packages (from botocore<2.0.0,>=1.31->sdv) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /usr/local/lib/python3.12/dist-packages (from botocore<2.0.0,>=1.31->sdv) (2.5.0)
Requirement already satisfied: plotly>=5.10.0 in /usr/local/lib/python3.12/dist-packages (from copulas>=0.12.1->sdv) (5.24.1)
Requirement already satisfied: scipy>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from copulas>=0.12.1->sdv) (1.16.3)
Requirement already satisfied: torch>=2.3.0 in /usr/local/lib/python3.12/dist-packages (from ctgan>=0.11.1->sdv) (2.10.0+cpu)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=2.1.1->sdv) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=2.1.1->sdv) (2025.3)
Requirement already satisfied: scikit-learn>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from rdt>=1.18.2->sdv) (1.6.1)
Collecting Faker!=37.11.0,>=17 (from rdt>=1.18.2->sdv)
  Downloading faker-40.11.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly>=5.10.0->copulas>=0.12.1->sdv) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly>=5.10.0->copulas>=0.12.1->sdv) (26.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil<3.0.0,>=2.1->botocore<2.0.0,>=1.31->sdv) (1.17.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.3.1->rdt>=1.18.2->sdv) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.3.1->rdt>=1.18.2->sdv) (3.6.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan>=0.11.1->sdv) (3.25.2)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan>=0.11.1->sdv) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan>=0.11.1->sdv) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan>=0.11.1->sdv) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan>=0.11.1->sdv) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan>=0.11.1->sdv) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan>=0.11.1->sdv) (2025.3.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.3.0->ctgan>=0.11.1->sdv) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.3.0->ctgan>=0.11.1->sdv) (3.0.3)
Downloading sdv-1.35.0-py3-none-any.whl (202 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 202.6/202.6 kB 9.9 MB/s eta 0:00:00
Downloading boto3-1.42.73-py3-none-any.whl (140 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.6/140.6 kB 11.6 MB/s eta 0:00:00
Downloading botocore-1.42.73-py3-none-any.whl (14.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.7/14.7 MB 64.6 MB/s eta 0:00:00
Downloading copulas-0.14.1-py3-none-any.whl (52 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.7/52.7 kB 4.8 MB/s eta 0:00:00
Downloading ctgan-0.12.1-py3-none-any.whl (25 kB)
Downloading deepecho-0.8.1-py3-none-any.whl (28 kB)
Downloading rdt-1.20.0-py3-none-any.whl (74 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.5/74.5 kB 6.1 MB/s eta 0:00:00
Downloading sdmetrics-0.28.0-py3-none-any.whl (202 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 202.3/202.3 kB 16.7 MB/s eta 0:00:00
Downloading faker-40.11.0-py3-none-any.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 75.5 MB/s eta 0:00:00
Downloading jmespath-1.1.0-py3-none-any.whl (20 kB)
Downloading s3transfer-0.16.0-py3-none-any.whl (86 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.8/86.8 kB 7.0 MB/s eta 0:00:00
Installing collected packages: jmespath, Faker, botocore, s3transfer, rdt, deepecho, copulas, sdmetrics, ctgan, boto3, sdv
Successfully installed Faker-40.11.0 boto3-1.42.73 botocore-1.42.73 copulas-0.14.1 ctgan-0.12.1 deepecho-0.8.1 jmespath-1.1.0 rdt-1.20.0 s3transfer-0.16.0 sdmetrics-0.28.0 sdv-1.35.0

{
    "METADATA_SPEC_VERSION": "SINGLE_TABLE_V1",
    "columns": {
        "Indicator": {
            "sdtype": "categorical"
        },
        "Year": {
            "sdtype": "numerical"
        },
        "Dimension": {
            "sdtype": "categorical"
        },
        "Value": {
            "sdtype": "numerical"
        }
    }
}

**Identify Column Types Explicitly**

In [ ]:
metadata.update_column(
    column_name='Indicator',
    sdtype='categorical'
)

metadata.update_column(
    column_name='Dimension',
    sdtype='categorical'
)

metadata.update_column(
    column_name='Year',
    sdtype='numerical'
)

metadata.update_column(
    column_name='Value',
    sdtype='numerical'
)

**Final Check Before GAN**

In [ ]:
print(df_final.info())
print(df_final.head())

<class 'pandas.core.frame.DataFrame'>
Index: 7351 entries, 1 to 15325
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Indicator  7351 non-null   object
 1   Year       7351 non-null   int64
 2   Dimension  7351 non-null   object
 3   Value      7351 non-null   float64
dtypes: float64(1), int64(1), object(2)
memory usage: 287.1+ KB
None
                                           Indicator  Year  \
1  Prevalence of overweight among children and ad...  2017
2  Proportion of population with primary reliance...  1995
4  Proportion of population with primary reliance...  2007
6  Prevalence of thinness among children and adol...  2005
8  Alcohol, recorded per capita (15+) consumption...  2018

                   Dimension      Value
1                     Female  28.953755
2                      Rural   4.400000
4                      Urban  82.400000
6                       Male   6.880980
8  Other alcoholic beverages   0.730000

**Key Notes (Important for the Paper)**



The dataset was preprocessed by removing missing values, standardizing variable formats, and selecting key features including health indicators, temporal attributes, demographic dimensions, and numerical values. Categorical variables were preserved in their original format to maintain semantic integrity for generative modelling, while numerical variables were optionally normalized to improve model stability. Additionally, feature reduction techniques were applied to limit high-cardinality categorical variables, thereby enhancing GAN training efficiency.

In [ ]:
!pip install sdv

Requirement already satisfied: sdv in /usr/local/lib/python3.12/dist-packages (1.35.0)
Requirement already satisfied: boto3<2.0.0,>=1.28 in /usr/local/lib/python3.12/dist-packages (from sdv) (1.42.73)
Requirement already satisfied: botocore<2.0.0,>=1.31 in /usr/local/lib/python3.12/dist-packages (from sdv) (1.42.73)
Requirement already satisfied: cloudpickle>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from sdv) (3.1.2)
Requirement already satisfied: graphviz>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from sdv) (0.21)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from sdv) (2.0.2)
Requirement already satisfied: pandas<3,>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from sdv) (2.2.2)
Requirement already satisfied: tqdm>=4.29 in /usr/local/lib/python3.12/dist-packages (from sdv) (4.67.3)
Requirement already satisfied: copulas>=0.12.1 in /usr/local/lib/python3.12/dist-packages (from sdv) (0.14.1)
Requirement already satisfied: ctgan>=0.11.1 in /usr/local/lib/python3.12/dist-packages (from sdv) (0.12.1)
Requirement already satisfied: deepecho>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from sdv) (0.8.1)
Requirement already satisfied: rdt>=1.18.2 in /usr/local/lib/python3.12/dist-packages (from sdv) (1.20.0)
Requirement already satisfied: sdmetrics>=0.28.0 in /usr/local/lib/python3.12/dist-packages (from sdv) (0.28.0)
Requirement already satisfied: platformdirs>=4.0 in /usr/local/lib/python3.12/dist-packages (from sdv) (4.9.4)
Requirement already satisfied: pyyaml>=6.0.1 in /usr/local/lib/python3.12/dist-packages (from sdv) (6.0.3)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from boto3<2.0.0,>=1.28->sdv) (1.1.0)
Requirement already satisfied: s3transfer<0.17.0,>=0.16.0 in /usr/local/lib/python3.12/dist-packages (from boto3<2.0.0,>=1.28->sdv) (0.16.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /usr/local/lib/python3.12/dist-packages (from botocore<2.0.0,>=1.31->sdv) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /usr/local/lib/python3.12/dist-packages (from botocore<2.0.0,>=1.31->sdv) (2.5.0)
Requirement already satisfied: plotly>=5.10.0 in /usr/local/lib/python3.12/dist-packages (from copulas>=0.12.1->sdv) (5.24.1)
Requirement already satisfied: scipy>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from copulas>=0.12.1->sdv) (1.16.3)
Requirement already satisfied: torch>=2.3.0 in /usr/local/lib/python3.12/dist-packages (from ctgan>=0.11.1->sdv) (2.10.0+cpu)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=2.1.1->sdv) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=2.1.1->sdv) (2025.3)
Requirement already satisfied: scikit-learn>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from rdt>=1.18.2->sdv) (1.6.1)
Requirement already satisfied: Faker!=37.11.0,>=17 in /usr/local/lib/python3.12/dist-packages (from rdt>=1.18.2->sdv) (40.11.0)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly>=5.10.0->copulas>=0.12.1->sdv) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly>=5.10.0->copulas>=0.12.1->sdv) (26.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil<3.0.0,>=2.1->botocore<2.0.0,>=1.31->sdv) (1.17.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.3.1->rdt>=1.18.2->sdv) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.3.1->rdt>=1.18.2->sdv) (3.6.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan>=0.11.1->sdv) (3.25.2)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan>=0.11.1->sdv) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan>=0.11.1->sdv) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan>=0.11.1->sdv) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan>=0.11.1->sdv) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan>=0.11.1->sdv) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan>=0.11.1->sdv) (2025.3.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.3.0->ctgan>=0.11.1->sdv) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.3.0->ctgan>=0.11.1->sdv) (3.0.3)